### ISSUE TITLE
poor concordance for indels but not SNPs

### ISSUE THREAD

**Issue by stsmall** [chapmanb/bcbio.variation#30]
Hi Brad,
Thanks for writing bcbio.variation!
I am attempting to use ensemble to create a SNP/Indel set from a GATK HaplotypeCaller and freebayes vcfs. Using the example config.yaml you provide in the README, I received the following statisitcs:
- PNG0018-1 : combo vs gatk
  |---------------------------+--------|
  |           Metric          |  Value |
  |---------------------------+--------|
  | concordant: total         | 118634 |
  | concordant: non-reference | 118634 |
  | concordant: SNPs          | 75050  |
  | concordant: indels        | 43390  |
  | combo-discordant: total   | 0      |
  | combo-discordant: SNPs    | 0      |
  | combo-discordant: indels  | 0      |
  | gatk-discordant: total    | 452    |
  | gatk-discordant: SNPs     | 397    |
  | gatk-discordant: indels   | 30     |
  | Shared discordant         | 452    |
  | het/hom discordant        | 416    |
  |---------------------------+--------|
  *\* Structural variation
  |----------------------------+-------|
  |           Metric           | Value |
  |----------------------------+-------|
  | sv-concordant: total       | 0     |
  | sv-combo-discordant: total | 0     |
  | sv-gatk-discordant: total  | 0     |
  |----------------------------+-------|
- PNG0018-1 : combo vs freebayes
  |------------------------------+-------|
  |            Metric            | Value |
  |------------------------------+-------|
  | concordant: total            | 69002 |
  | concordant: non-reference    | 69002 |
  | concordant: SNPs             | 66135 |
  | concordant: indels           | 1414  |
  | combo-discordant: total      | 0     |
  | combo-discordant: SNPs       | 0     |
  | combo-discordant: indels     | 0     |
  | freebayes-discordant: total  | 33164 |
  | freebayes-discordant: SNPs   | 499   |
  | freebayes-discordant: indels | 27945 |
  | Shared discordant            | 41290 |
  | het/hom discordant           | 185   |
  |------------------------------+-------|
  *\* Structural variation
  |--------------------------------+-------|
  |             Metric             | Value |
  |--------------------------------+-------|
  | sv-concordant: total           | 0     |
  | sv-combo-discordant: total     | 0     |
  | sv-freebayes-discordant: total | 0     |
  |--------------------------------+-------|
- PNG0018-1 : gatk vs freebayes
  |------------------------------+-------|
  |            Metric            | Value |
  |------------------------------+-------|
  | concordant: total            | 58691 |
  | concordant: non-reference    | 58691 |
  | concordant: SNPs             | 58691 |
  | concordant: indels           | 0     |
  | gatk-discordant: total       | 60395 |
  | gatk-discordant: SNPs        | 16756 |
  | gatk-discordant: indels      | 43420 |
  | freebayes-discordant: total  | 43475 |
  | freebayes-discordant: SNPs   | 7943  |
  | freebayes-discordant: indels | 29359 |
  | Shared discordant            | 42865 |
  | het/hom discordant           | 601   |
  |------------------------------+-------|
  *\* Structural variation
  |--------------------------------+-------|
  |             Metric             | Value |
  |--------------------------------+-------|
  | sv-concordant: total           | 0     |
  | sv-gatk-discordant: total      | 0     |
  | sv-freebayes-discordant: total | 0     |
  |--------------------------------+-------|
- PNG0018-1 : combo vs all
  |-------------------------------+-------|
  |             Metric            | Value |
  |-------------------------------+-------|
  | true-positives: total         | 58691 |
  | true-positives: non-reference | 58691 |
  | true-positives: SNPs          | 58691 |
  | true-positives: indels        | 0     |
  | false-negatives: total        | 58691 |
  | false-negatives: SNPs         | 58691 |
  | false-negatives: indels       | 0     |
  | false-positives: total        | 70254 |
  | false-positives: SNPs         | 23803 |
  | false-positives: indels       | 44804 |
  | Shared discordant             | 23    |
  | het/hom discordant            | 0     |
  |-------------------------------+-------|
- PNG0018-1 : combo-recal vs gatk
  |--------------------------------+--------|
  |             Metric             |  Value |
  |--------------------------------+--------|
  | concordant: total              | 118634 |
  | concordant: non-reference      | 118634 |
  | concordant: SNPs               | 75050  |
  | concordant: indels             | 43390  |
  | combo-recal-discordant: total  | 10311  |
  | combo-recal-discordant: SNPs   | 7444   |
  | combo-recal-discordant: indels | 1417   |
  | gatk-discordant: total         | 452    |
  | gatk-discordant: SNPs          | 397    |
  | gatk-discordant: indels        | 30     |
  | Shared discordant              | 452    |
  | het/hom discordant             | 416    |
  |--------------------------------+--------|
  *\* GATK recalibration filter metrics

I also tried running a normalization piperline (vcflib > vt normalize) on the freebayes vcf before using ensemble. This produced the same output as above. I also tried altering the classifiers from [AD, PL, DP] to include [AO, GQ, DPR, FS]. This produced an error: 
Filter VCF with {{:variant-type :snp, :attr-key :all, :zygosity :hom} nil, {:variant-type :snp, :attr-key :all, :zygosity :het} nil, {:variant-type :complex, :attr-key :all, :zygosity :hom} nil, {:variant-type :complex, :attr-key :all, :zygosity :het} nil}
Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String

What would you suggest i do?
Should I include more detailed classifiers, like "balance" and "calling" in addition to "general"?
thanks,
scott

**Comment by chapmanb** [comment]
Scott;
Thanks for trying out the ensemble calling and for the detailed question. Ensemble calling is not very effective without 3 or more calling inputs. The primary driver of the outputs is the selection of x out of n samples, and with only 2 it's hard to resolve beyond doing a union (which tends to be too liberal) or intersection (which tends to be too conservative). We found the extra work of training a classifier helps some but also is hard to generalize to lots of datasets.

We have a simpler method that only implements the x out of n approach which you could also use if you run into problems with this:

https://github.com/chapmanb/bcbio.variation.recall#ensemble

Hope this helps.
